# Generated by Django 4.2.5 on 2024-02-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0003_userprofile_total_race_time_delete_totaltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=100)),
                ('lap_time', models.CharField(max_length=10)),
            ],
        ),
    ]
