# Generated by Django 4.2.5 on 2024-02-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0005_laptimeentrys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LapTimeEntrys',
        ),
    ]
