# Generated by Django 4.2.5 on 2024-02-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceApp', '0006_delete_laptimeentrys'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacingRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('license_pdf', models.FileField(upload_to='license_pdfs/')),
            ],
        ),
    ]
